### ISSUE TITLE
`scaling` parameter is missing some validation

### ISSUE THREAD

**Issue by ev-br** [nmayorov/bounded-lsq#5]
```
>>> import numpy as np
>>> from scipy.optimize import least_squares
>>> def f(x):
...    return x - 1.
... 
>>> least_squares(f, x0=2., scaling=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/scipy/optimize/least_squares.py", line 520, in least_squares
    verbose)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/scipy/optimize/_lsq_trf.py", line 311, in trf
    U, s, V = svd(J_augmented, full_matrices=False)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/scipy/linalg/decomp_svd.py", line 88, in svd
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/scipy/_lib/_util.py", line 138, in _asarray_validated
    a = toarray(a)
  File "/home/br/virtualenvs/scipy-dev/local/lib/python2.7/site-packages/numpy/lib/function_base.py", line 612, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
```

Should be trivial to guard against.

**Comment by nmayorov** [comment]
Good catch. Need to add some check like "is_numbers" and `is_finite`.

**Comment by ev-br** [comment]
I'd delegate checking `is_number_like` to numpy as well:

```
>>> np.isfinite(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> 
```

**Comment by nmayorov** [comment]
I noticed this thing too. But I decided also to check against complex numbers. It's wired I know, but who knows what will happen.

```
    if not np.all(np.isreal(scaling)):
        raise ValueError("`scaling` must contain real values.")

    if not np.all(np.isfinite(scaling)):
        raise ValueError("`scaling` must contain finite values.")
```

Is it OK?

**Comment by ev-br** [comment]
Yup, good point.

**Comment by nmayorov** [comment]
The final variant (checking for complex is done in `asarray`):

```
    try:
        scaling = np.asarray(scaling, dtype=float)
        valid = np.all(np.isfinite(scaling)) and np.all(scaling > 0)
    except (ValueError, TypeError):
        valid = False

    if not valid:
        raise ValueError("`scaling` must be 'jac' or array_like with "
                         "positive numbers.")
```
